version: "3.9"
services:
  sftp:
    image: atmoz/sftp:latest
    container_name: local_sftp
    ports:
      - "2222:22"
    volumes:
      - ./sftp-data/Swikriti/upload:/home/Swikriti/upload
    command: Swikriti:password:1001:100
    restart: unless-stopped
